### ISSUE TITLE
AngularGradient ?

### ISSUE THREAD

**Issue by JulesMoorhouse** [ArnavMotwani/CircularProgressSwiftUI#2]
Hey,

It would be awesome if this supported AngularGradients too.

![](https://www.hackingwithswift.com/img/books/quick-start/swiftui/how-to-render-a-gradient-6~dark@2x.png)

https://www.hackingwithswift.com/quick-start/swiftui/how-to-render-a-gradient

Thanks,

Jules.

**Comment by ArnavMotwani** [comment]
Gonna work on it!

**Comment by ArnavMotwani** [comment]
Added the feature

**Comment by JulesMoorhouse** [comment]
@ArnavMotwani I've just been trying this.
But unfortunately I need to support iOS 14 🙁 

Such a shame.

I don't suppose iOS 15 is essential ?

On an unrelated issue, I'm getting some `Swift Compiler Errors` which archiving my project from the `CircularProgressSwiftUI` library. 

I normally use Xcode 12.5, but I've tried Xcode 13.2, but the errors persist.

Here's some related posts...

https://developer.apple.com/forums/thread/690907
https://developer.apple.com/forums/thread/662247

**Comment by JulesMoorhouse** [comment]
This fixes the issue ... in v1.1.0

https://github.com/cpytel/CircularProgressSwiftUI/commit/14f38354d4fe279264bca0a6dd617b5573fbdcf4

**Comment by ArnavMotwani** [comment]
Ah okay so a lot of things are happening here so ill cover them one at a time:
1. To support AngularGradients are unfortunately a different type than LinearGradients. I didn't want to create a new View for just this one change so I decided to just decided to change the type of the Fill parameter to support both. Since they both conform to ShapeStyle I could us the AnyShapeStyle Type but that is new to SwiftUI in iOS 15.
2. Can you share the compiler log or a screenshot of the error.
3. I can't add the platforms to the project as Apple hasn't added the iOS 15 and macOS 12 tags yet. Im trying to figure it out.

**Comment by JulesMoorhouse** [comment]
Literally you get lots of 'Swift Compiler Error', for all things including view. Pretty much everything in the main SwiftUI view.

As I say adding iOS 15 to the packages file fixes the problem.

I’ve forked your repo, added that fix and can only use v1.1.0.

Would love to see iOS 14 backward compatibility.

Thanks.

**Comment by ArnavMotwani** [comment]
@JulesMoorhouse I just added a new branch for iOS 13 onwards. Right now that should build properly and I might add the angular gradient to that branch as well.

**Comment by JulesMoorhouse** [comment]
@ArnavMotwani awesome, thank you.

I think for most people they won’t be having a minimum ios target of 15 for a year.

Let me know when you’ve done that.

👍
